let codeArea = document.querySelector("#codeArea");
let codeMirror = CodeMirror.fromTextArea(codeArea, {
  mode: "text/x-java",
  theme: "barista",
  lineNumbers: true,
  autofocus: true,
  tabSize: 2
});

//sets the content of the coding-interface from a click
function loadContent() {
  codeMirror.setValue(window.persistenceService.getContentToOpen());
  return window.persistenceService.getContentToOpen();
}

//sets the content of the coding-interface from a drag
function switchContent(){
  codeMirror.setValue(window.persistenceService.getContentToSwitch());
  return window.persistenceService.getContentToSwitch();
}

//gets the content of the coding-interface
function getContent() {
  return codeMirror.getValue();
}

//returns the line, the cursor is in
function getCursorLine() {
  return codeMirror.getCursor().line;
}

//inserts content generated by the Java app
function insertGeneratedContent(){
  content = window.persistenceService.getGeneratedContent();
  line = window.persistenceService.getGenerateInsertPosition() < 1 ? 1 : window.persistenceService.getGenerateInsertPosition() - 1;
  ch = codeMirror.getLine(line).length
  codeMirror.replaceRange(content, {line, length})
}

function activateJavaMode(){
  codeMirror.setOption("mode", "text/x-java");
}

function activateTextMode(){
 codeMirror.setOption("mode", "text/plain");
}
